{% set version = "1.0.5" %}

package:
  name: lightpath-suite
  version: {{ version }}

source:
  url: https://github.com/pcdshub/lightpath/archive/v{{ version }}.tar.gz
  sha256: 0cadb7e244f633f5675a2586d61f6cf31419d19f6de064292a7a17e5505ee4d7

build:
  entry_points:
    - lightpath = lightpath.main:entrypoint
  number: 1

requirements:
  host:
    - python >=3.9

test:
  imports:
    - lightpath

outputs:
  - name: lightpath-base
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm
      run:
        - python >={{ python_min }}
        - coloredlogs
        - happi >=1.6.0
        - ophyd
        - prettytable
      run_constrained:
        - networkx <3.3  # [py<=39]

  - name: lightpath
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
        - setuptools_scm
      run:
        - {{ pin_subpackage('lightpath-base', max_pin='x.x.x') }}
        - pydm
        - pyqt >=5
        - qtawesome
        - qtpy
        - typhos >=1.0.0
      test:
        requires:
          - python {{ python_min }}
        imports:
          - lightpath

about:
  home: https://github.com/pcdshub/lightpath
  doc_url: https://pcdshub.github.io/lightpath
  dev_url: https://github.com/pcdshub/lightpath
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: Linac Coherent Light Source (LCLS) beamline configuration and control

extra:
  feedstock-name: lightpath
  recipe-maintainers:
    - conda-forge/pcdsdevices
