{% set name = "lightpath" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/lightpath/archive/v{{ version }}.tar.gz
  sha256: 94c12a7a79a2f82bcb43c36ef809a0eabdccf6b2889dde5834b2973881dbb0d4

build:
  entry_points:
    - lightpath = lightpath.main:entrypoint
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - coloredlogs
    - happi >=1.6.0
    - numpy
    - ophyd
    - pcdsdevices >=3.4.0
    - prettytable
    - pydm
    - pyqt >=5
    - qtawesome
    - qtpy
    - typhos >=1.0.0

test:
  imports:
    - lightpath

about:
  home: https://github.com/pcdshub/lightpath
  doc_url: https://pcdshub.github.io/lightpath
  dev_url: https://github.com/pcdshub/lightpath
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: Linac Coherent Light Source (LCLS) beamline configuration and control

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
    - tangkong
    - klauer
    - ZLLentz
